version: '3.8'

services:
  backend:
    container_name: scriptingbot-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    stdin_open: true
    tty: true
